server:
  port: 8080
spring:
  application:
    name: osprey-partners
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
