// English-only for v1. Gathered in one module so retrofitting the fleet's five-language
// i18n is a mechanical swap. TODO(ADR-0009): wire i18next like the other portals.
export const strings = {
  title: "Route Explorer",
  tabExplore: "Explore",
  tabRouteSearch: "Route search",
  tabMap: "Map",
  searchPlaceholder: "Search airports by name, city or IATA…",
  fromLabel: "From",
  toLabel: "To",
  optimizeLabel: "Optimize for",
  optimizeKm: "Distance",
  optimizeMin: "Flight time",
  optimizeHops: "Fewest stops",
  searchButton: "Find route",
  noRouteFound: "No route found within six hops.",
  legsHeading: "Itinerary",
  totalSummary: "{hops} hop(s) · {km} km · {duration}",
  pointsBadge: "≈ {points} Osprey points",
  mapUnavailable: "Map unavailable — build the WASM island with: npm run build:wasm",
  mapSelected: "Routes from {iata}",
  searchEmpty: "No airports match.",
  destinationsHeading: "Direct destinations from",
  colDestination: "Destination",
  colCountry: "Country",
  colDistance: "Distance",
  colDuration: "Flight time",
  colCarriers: "Carriers",
  noCarriers: "—",
  loadFailed: "Something went wrong talking to the gateway. Try again.",
  loading: "Loading…",
} as const;
